version: "3.8"

services:
  app:
    build: .
    container_name: next-app
    restart: always
    networks:
      - next-net

  nginx:
    image: nginx:latest
    container_name: next-nginx
    restart: always
    ports:
      - "38080:38080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - next-net

networks:
  next-net:
    driver: bridge
